authentication/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

djtravel/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('travelapp.urls')),
    path('authentication/', include('authentication.urls')),
]

travelapp/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = "travel"

urlpatterns = [
    path('', views.index, name="home"),
    path('about', views.about, name="about"),
    path('services', views.services, name="services"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/models.py
from django.db import models

# Create your models here.

travelapp/models.py
from django.db import models

# Create your models here.

class Destination(models.Model):
    name = models.CharField(max_length=100)
    desc = models.TextField()
    image = models.ImageField(upload_to='uploads')
    price_from = models.DecimalField(decimal_places=2, max_digits=5, null=True)

    def __str__(self):
        return self.name
    


class Member(models.Model):
    name = models.CharField(max_length=100)
    bio = models.TextField()
    image = models.ImageField(upload_to='members')

    def __str__(self):
        return self.name
    

authentication/views.py
from django.contrib.auth.models import User
from django.contrib import messages,auth
from django.shortcuts import redirect, render

# Create your views here.

def register(request):
    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        username = request.POST['username']
        email = request.POST['email']
        password1 = request.POST['password1']
        password2 = request.POST['password2']

        if password1 == password2:
            if User.objects.filter(username=username).exists():
                messages.info(request, 'Username is already taken')
                return redirect('register')
            if User.objects.filter(email=email).exists():
                messages.info(request, 'Email is already taken')
                return redirect('register')
            user = User.objects.create_user(first_name=first_name, last_name=last_name, username=username, email=email, password=password1)
            user.save()
            print('User Registered')
            return redirect('login')
        else:
            messages.info(request, 'Password doesn\'t match')
            return redirect('register')
        
    return render(request, 'register.html')


def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user);
            return redirect('/')
        else:
            messages.info(request, "Invalid credentails")
            return redirect('login')    

    return render(request, 'login.html')    


def logout(request):
    auth.logout(request)
    return redirect('/')

travelapp/views.py
from django.shortcuts import render
from .models import Destination, Member

# Create your views here.

def index(request):
    destinations = Destination.objects.all()
    members = Member.objects.all()
    context = {
        'destinations': destinations,
        'members': members
    }
    return render(request, 'index.html', context)

def about(request):
    return render(request, 'about.html')


def services(request):
    return render(request, 'sevices.html')

templates/about.html
{% extends 'base.html' %}

{% block 'title' %}Travello | About Us{% endblock  %}

{% load static %}

{% block 'content' %}
<div class="about">
    <div class="container">
        <p>Pellentesque sit amet elementum ccumsan sit amet mattis eget, tristique at leo. Vivamus massa.Tempor massa et laoreet .Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu laoreet ante, sollicitudin volutpat quam. Vestibulum posuere malesuada ultrices. In pulvinar rhoncus lacus at aliquet. Nunc vitae lacus varius, auctor nisi sit amet, consectetur mauris. Curabitur sodales semper est, vel faucibus urna laoreet vel. Ut justo diam, sodales non pulvinar at, vulputate quis neque. Etiam aliquam purus vel ultricies consequat.</p>
    </div>
</div>        
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<title>{% block 'title' %}{% endblock  %}</title>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="description" content="Travello template project">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="{% static 'styles/bootstrap4/bootstrap.min.css' %}">
<link href="{% static 'plugins/font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/owl.carousel.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/owl.theme.default.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/animate.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/about.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/contact.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/about_responsive.css' %}">
</head>
<body>

<div class="super_container">
	
	<!-- Header -->

	<header class="header">
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="header_content d-flex flex-row align-items-center justify-content-start">
						<div class="header_content_inner d-flex flex-row align-items-end justify-content-start">
							<div class="logo"><a href=" {% url 'travel:home' %} ">Travello</a></div>
							<nav class="main_nav">
								<ul class="d-flex flex-row align-items-start justify-content-start">
									<li {% if request.resolver_match.url_name == 'home' %}class="active"{% endif %}><a href=" {% url 'travel:home' %} ">Home</a></li>
									<li {% if request.resolver_match.url_name == 'about' %}class="active"{% endif %}><a href="{% url 'travel:about' %}">About us</a></li>
									<li {% if request.resolver_match.url_name == 'services' %}class="active"{% endif %}><a href="{% url 'travel:services' %}">Services</a></li>
									{% if user.is_authenticated %}
										<li><a href="#">Hello, {{ user.username }}</a></li>
										<li><a href="{% url 'logout' %}">Logout</a></li>
									{% else %}
										<li {% if request.resolver_match.url_name == 'register' %}class="active"{% endif %}><a href="{% url 'register' %}">Register</a></li>
										<li {% if request.resolver_match.url_name == 'login' %}class="active"{% endif %}><a href="{% url 'login' %}">Login</a></li>	
									{% endif %}
								</ul>
							</nav>
							<div class="header_phone ml-auto">Call us: 00-56 445 678 33</div>

							<!-- Hamburger -->

							<div class="hamburger ml-auto">
								<i class="fa fa-bars" aria-hidden="true"></i>
							</div>

						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="header_social d-flex flex-row align-items-center justify-content-start">
			<ul class="d-flex flex-row align-items-start justify-content-start">
				<li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
				<li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
				<li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
				<li><a href="#"><i class="fa fa-dribbble" aria-hidden="true"></i></a></li>
				<li><a href="#"><i class="fa fa-behance" aria-hidden="true"></i></a></li>
				<li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
			</ul>
		</div>
	</header>

	<!-- Menu -->

	<div class="menu">
		<div class="menu_header d-flex flex-row align-items-center justify-content-start">
			<div class="menu_logo"><a href="index.html">Travello</a></div>
			<div class="menu_close_container ml-auto"><div class="menu_close"><div></div><div></div></div></div>
		</div>
		<div class="menu_content">
			<ul>
				<li><a href="inex.html">Home</a></li>
				<li><a href="about.html">About us</a></li>
				<li><a href="#">Services</a></li>
				<li><a href="news.html">News</a></li>
				<li><a href="contact.html">Contact</a></li>
			</ul>
		</div>
		<div class="menu_social">
			<div class="menu_phone ml-auto">Call us: 00-56 445 678 33</div>
			<ul class="d-flex flex-row align-items-start justify-content-start">
				<li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
				<li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
				<li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
				<li><a href="#"><i class="fa fa-dribbble" aria-hidden="true"></i></a></li>
				<li><a href="#"><i class="fa fa-behance" aria-hidden="true"></i></a></li>
				<li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
			</ul>
		</div>
	</div>
	
	<!-- Home -->

	<div class="home">
		<div class="background_image" style="background-image:url({% static 'images/about.jpg' %})"></div>
	</div>

	<!-- Search -->

	<div class="home_search">
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="home_search_container">
						<div class="home_search_title">Search for your trip</div>
						<div class="home_search_content">
							<form action="#" class="home_search_form" id="home_search_form">
								<div class="d-flex flex-lg-row flex-column align-items-start justify-content-lg-between justify-content-start">
									<input type="text" class="search_input search_input_1" placeholder="City" required="required">
									<input type="text" class="search_input search_input_2" placeholder="Departure" required="required">
									<input type="text" class="search_input search_input_3" placeholder="Arrival" required="required">
									<input type="text" class="search_input search_input_4" placeholder="Budget" required="required">
									<button class="home_search_button">search</button>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>


	<!-- Why Choose Us -->
	{% block 'content' %}{% endblock  %}
	

	<!-- Footer -->

	<footer class="footer">
		<div class="parallax_background parallax-window" data-parallax="scroll" data-image-src="{% static 'images/footer_1.jpg' %}" data-speed="0.8"></div>
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="newsletter">
						<div class="newsletter_title_container text-center">
							<div class="newsletter_title">Subscribe to our newsletter to get the latest trends & news</div>
							<div class="newsletter_subtitle">Join our database NOW!</div>
						</div>
						<div class="newsletter_form_container">
							<form action="#" class="newsletter_form d-flex flex-md-row flex-column align-items-start justify-content-between" id="newsletter_form">
								<div class="d-flex flex-md-row flex-column align-items-start justify-content-between">
									<div><input type="text" class="newsletter_input newsletter_input_name" id="newsletter_input_name" placeholder="Name" required="required"><div class="input_border"></div></div>
									<div><input type="email" class="newsletter_input newsletter_input_email" id="newsletter_input_email" placeholder="Your e-mail" required="required"><div class="input_border"></div></div>
								</div>
								<div><button class="newsletter_button">subscribe</button></div>
							</form>
						</div>
					</div>
				</div>
			</div>
			<div class="row footer_contact_row">
				<div class="col-xl-10 offset-xl-1">
					<div class="row">

						<!-- Footer Contact Item -->
						<div class="col-xl-4 footer_contact_col">
							<div class="footer_contact_item d-flex flex-column align-items-center justify-content-start text-center">
								<div class="footer_contact_icon"><img src="{% static 'images/sign.svg' %}" alt=""></div>
								<div class="footer_contact_title">give us a call</div>
								<div class="footer_contact_list">
									<ul>
										<li>Office Landline: +44 5567 32 664 567</li>
										<li>Mobile: +44 5567 89 3322 332</li>
									</ul>
								</div>
							</div>
						</div>

						<!-- Footer Contact Item -->
						<div class="col-xl-4 footer_contact_col">
							<div class="footer_contact_item d-flex flex-column align-items-center justify-content-start text-center">
								<div class="footer_contact_icon"><img src="{% static 'images/trekking.svg' %}" alt=""></div>
								<div class="footer_contact_title">come & drop by</div>
								<div class="footer_contact_list">
									<ul style="max-width:190px">
										<li>4124 Barnes Street, Sanford, FL 32771</li>
									</ul>
								</div>
							</div>
						</div>

						<!-- Footer Contact Item -->
						<div class="col-xl-4 footer_contact_col">
							<div class="footer_contact_item d-flex flex-column align-items-center justify-content-start text-center">
								<div class="footer_contact_icon"><img src="{% static 'images/trekking.svg' %}" alt=""></div>
								<div class="footer_contact_title">send us a message</div>
								<div class="footer_contact_list">
									<ul>
										<li>youremail@gmail.com</li>
										<li>Office@yourbusinessname.com</li>
									</ul>
								</div>
							</div>
						</div>

					</div>
				</div>
			</div>
		</div>
		<div class="col text-center"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --> </div>

	</footer>
</div>

<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'styles/bootstrap4/popper.js' %}"></script>
<script src="{% static 'styles/bootstrap4/bootstrap.min.js' %}"></script>
<script src="{% static 'plugins/greensock/TweenMax.min.js' %}"></script>
<script src="{% static 'plugins/greensock/TimelineMax.min.js' %}"></script>
<script src="{% static 'plugins/scrollmagic/ScrollMagic.min.js' %}"></script>
<script src="{% static 'plugins/greensock/animation.gsap.min.js' %}"></script>
<script src="{% static 'plugins/greensock/ScrollToPlugin.min.js' %}"></script>
<script src="{% static 'plugins/OwlCarousel2-2.2.1/owl.carousel.js' %}"></script>
<script src="{% static 'plugins/easing/easing.js' %}"></script>
<script src="{% static 'plugins/parallax-js-master/parallax.min.js' %}"></script>
<script src="{% static 'js/about.js' %}"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block 'title' %}Travello | Home{% endblock  %}

{% load static %}

{% block 'content' %}

<!-- About -->

<div class="about">
    <div class="container">
        <div class="row">
            <div class="col text-center">
                <div class="section_subtitle">simply amazing places</div>
                <div class="section_title"><h2>A few words about us</h2></div>
            </div>
        </div>
        <div class="row about_row">
            <div class="col-lg-6">
                <div class="about_content">
                    <div class="text_highlight">Pellentesque sit amet elementum ccumsan sit amet mattis eget, tristique at leo. Vivamus massa.Tempor massa et laoreet .Lorem ipsum dolor sit amet, consectetur adipiscing elit.</div>
                    <div class="about_text">
                        <p>Pellentesque sit amet elementum ccumsan sit amet mattis eget, tristique at leo. Vivamus massa.Tempor massa et laoreet .Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu laoreet ante, sollicitudin volutpat quam. Vestibulum posuere malesuada ultrices. In pulvinar rhoncus lacus at aliquet. Nunc vitae lacus varius, auctor nisi sit amet, consectetur mauris. Curabitur sodales semper est, vel faucibus urna laoreet vel. Ut justo diam, sodales non pulvinar at, vulputate quis neque. Etiam aliquam purus vel ultricies consequat.</p>
                    </div>
                    <div class="button about_button"><a href="#">read more</a></div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="about_image"><img src="{% static 'images/about_1.jpg' %}" alt=""></div>
            </div>
        </div>
    </div>
</div>

<!-- Milestones -->

<div class="milestones">
    <div class="container">
        <div class="row">
            
            <!-- Milestone -->
            <div class="col-lg-3 milestone_col">
                <div class="milestone text-center">
                    <div class="milestone_icon"><img src="{% static 'images/mountain.svg' %}" alt=""></div>
                    <div class="milestone_counter" data-end-value="17">0</div>
                    <div class="milestone_text">Online Courses</div>
                </div>
            </div>

            <!-- Milestone -->
            <div class="col-lg-3 milestone_col">
                <div class="milestone text-center">
                    <div class="milestone_icon"><img src="{% static 'images/island.svg' %}" alt=""></div>
                    <div class="milestone_counter" data-end-value="213">0</div>
                    <div class="milestone_text">Students</div>
                </div>
            </div>

            <!-- Milestone -->
            <div class="col-lg-3 milestone_col">
                <div class="milestone text-center">
                    <div class="milestone_icon"><img src="{% static 'images/camera.svg' %}" alt=""></div>
                    <div class="milestone_counter" data-end-value="11923">0</div>
                    <div class="milestone_text">Teachers</div>
                </div>
            </div>

            <!-- Milestone -->
            <div class="col-lg-3 milestone_col">
                <div class="milestone text-center">
                    <div class="milestone_icon"><img src="{% static 'images/boat.svg' %}" alt=""></div>
                    <div class="milestone_counter" data-end-value="15">0</div>
                    <div class="milestone_text">Countries</div>
                </div>
            </div>

        </div>
    </div>
</div>
<div class="why">
    <div class="parallax_background parallax-window" data-parallax="scroll" data-image-src="{% static 'images/why.jpg' %}" data-speed="0.8"></div>
    <div class="container">
        <div class="row">
            <div class="col text-center">
                <div class="section_subtitle">simply amazing places</div>
                <div class="section_title"><h2>Destinations</h2></div>
            </div>
        </div>
        <div class="row why_row">
            
            <!-- Why item -->
            {% for destination in destinations %}
            <div class="col-lg-4 why_col">
                <div class="why_item">
                    <div class="why_image">
                        <img src="{{ destination.image.url }}" alt="">
                        <div class="why_icon d-flex flex-column align-items-center justify-content-center">
                            <img src="{% static 'images/why_1.svg' %}" alt="">
                        </div>
                    </div>
                    <div class="why_content text-center">
                        <div class="why_title">{{ destination.name }}</div>
                        <div class="why_text">
                            <p>Starts from <b>${{ destination.price_from }}</b></p>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

<!-- Team -->

<div class="team">
    <div class="container">
        <div class="row">
            <div class="col text-center">
                <div class="section_subtitle">simply amazing people</div>
                <div class="section_title"><h2>Meet the Team</h2></div>
            </div>
        </div>
        <div class="row team_row">
            {% for member in members %}
                <!-- Team Item -->
                <div class="col-xl-3 col-md-6 team_col">
                    <div class="team_item d-flex flex-column align-items-center justify-content-start text-center">
                        <div class="team_image"><img src="{{ member.image.url }}" alt=""></div>
                        <div class="team_content">
                            <div class="team_title"><a href="#">{{ member.name }}</a></div>
                            <div class="team_text">
                                <p>{{ member.bio }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock  %}

templates/login.html
{% extends 'base.html' %}

{% block 'title' %}Travello | Login{% endblock  %}

{% load static %}

{% block 'content' %}
<div class="contact">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h2 class="contact-title">Travello Login</h2>
            </div>
            <div class="col-lg-12">
                <div class="contact_form_container">
                    <form action="/authentication/login/" id="contact_form" class="contact_form" method="POST">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-lg-12" style="margin-bottom: 18px">
                                <div><input type="text" class="contact_input contact_input_subject inpt" name="username" placeholder="Username" required="required"><div class="input_border"></div></div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12" style="margin-bottom: 18px">
                                <div><input type="password" class="contact_input contact_input_email inpt" name="password" placeholder="Password" required="required"><div class="input_border"></div></div>
                            </div>
                        </div>
                        <button type="submit" class="contact_button">Login</button>
                    </form>
                </div>
            </div>
            <div class="col-lg-12" style="margin-top: 18px">
                {% for msg in messages %}
                    <div class="alert alert-danger" role="alert">{{ msg }}</div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/register.html
{% extends 'base.html' %}

{% block 'title' %}Travello | Register{% endblock  %}

{% load static %}

{% block 'content' %}
<div class="contact">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h2 class="contact-title">Create An Account</h2>
            </div>
            <div class="col-lg-12">
                <div class="contact_form_container">
                    <form action="/authentication/register/" id="contact_form" class="contact_form" method="POST">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-lg-6" style="margin-bottom: 18px">
                                <div><input type="text" class="contact_input contact_input_email inpt" name="first_name" placeholder="First Name" required="required"><div class="input_border"></div></div>
                            </div>
                            <div class="col-lg-6" style="margin-bottom: 18px">
                                <div><input type="text" class="contact_input contact_input_subject inpt" name="last_name" placeholder="Last Name" required="required"><div class="input_border"></div></div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-6" style="margin-bottom: 18px">
                                <div><input type="email" class="contact_input contact_input_email inpt" name="email" placeholder="Your E-mail" required="required"><div class="input_border"></div></div>
                            </div>
                            <div class="col-lg-6" style="margin-bottom: 18px">
                                <div><input type="text" class="contact_input contact_input_subject inpt" name="username" placeholder="Username" required="required"><div class="input_border"></div></div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-6" style="margin-bottom: 18px">
                                <div><input type="password" class="contact_input contact_input_email inpt" name="password1" placeholder="Password" required="required"><div class="input_border"></div></div>
                            </div>
                            <div class="col-lg-6" style="margin-bottom: 18px">
                                <div><input type="password" class="contact_input contact_input_subject inpt" name="password2" placeholder="Confirm Password" required="required"><div class="input_border"></div></div>
                            </div>
                        </div>
                        <button type="submit" class="contact_button">Signup</button>
                    </form>
                </div>
            </div>
            <div class="col-lg-12" style="margin-top: 18px">
                {% for msg in messages %}
                    <div class="alert alert-danger" role="alert">{{ msg }}</div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/sevices.html
{% extends 'base.html' %}

{% block 'title' %}Travello | Sevices{% endblock  %}

{% load static %}

{% block 'content' %}
<div class="about">
    <div class="container">
        <p>Pellentesque sit amet elementum ccumsan sit amet mattis eget, tristique at leo. Vivamus massa.Tempor massa et laoreet .Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu laoreet ante, sollicitudin volutpat quam. Vestibulum posuere malesuada ultrices. In pulvinar rhoncus lacus at aliquet. Nunc vitae lacus varius, auctor nisi sit amet, consectetur mauris. Curabitur sodales semper est, vel faucibus urna laoreet vel. Ut justo diam, sodales non pulvinar at, vulputate quis neque. Etiam aliquam purus vel ultricies consequat.</p>
    </div>
</div> 
{% endblock %}